#!/usr/bin/env python3
"""Stop hook — saves session summary and observation YAML draft (HOOK-03)."""
import datetime
import json
import os
import pathlib
import sys

sys.path.insert(0, os.path.dirname(__file__))
from reprogate_hook_base import check_disabled, get_profile

ROOT = pathlib.Path(__file__).resolve().parents[2]
SESSION_DATA = ROOT / ".claude" / "session-data"


def main(session_data: pathlib.Path | None = None) -> int:
    check_disabled()
    data_dir = session_data or SESSION_DATA
    data_dir.mkdir(parents=True, exist_ok=True)
    now = datetime.datetime.utcnow().strftime("%Y%m%dT%H%M%SZ")
    profile = get_profile()

    # Load current session if exists
    current: dict = {}
    current_path = data_dir / "current-session.json"
    if current_path.exists():
        try:
            current = json.loads(current_path.read_text(encoding="utf-8"))
        except Exception:
            current = {}

    session_id = current.get("session_id", f"sess-{now}")
    tool_calls = current.get("tool_calls", [])

    # Save summary JSON
    summary = {
        "session_id": session_id,
        "ended_at": now,
        "profile": profile,
        "tool_calls_count": len(tool_calls),
    }
    (data_dir / f"session-{now}-summary.json").write_text(
        json.dumps(summary, indent=2), encoding="utf-8"
    )

    # Save observation YAML draft
    obs_yaml = (
        f"observation_id: obs-{now}\n"
        f"session_id: {session_id}\n"
        f"captured_at: \"{now}\"\n"
        f"profile: {profile}\n"
        f"tool_calls_count: {len(tool_calls)}\n"
        "instincts: []\n"
        "notes: \"Auto-generated by Stop hook. Review and promote via /rg:learn-eval.\"\n"
    )
    (data_dir / f"session-{now}-observation.yaml").write_text(obs_yaml, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
