#!/usr/bin/env python3
"""Stop hook — saves session summary and observation YAML draft (HOOK-03).

Skill Evolution (SKILL-EVO-01): Stop hook saves a structured observation
template to ~/.claude/homunculus/instincts/ for later review via /rg:learn-eval.
LLM-assisted instinct extraction is deferred to review time (ADR-016).
"""
import datetime
import json
import os
import pathlib
import sys
import uuid

sys.path.insert(0, os.path.dirname(__file__))
from reprogate_hook_base import check_disabled, get_profile

ROOT = pathlib.Path(__file__).resolve().parents[2]
SESSION_DATA = ROOT / ".claude" / "session-data"
HOMUNCULUS_INSTINCTS = pathlib.Path.home() / ".claude" / "homunculus" / "instincts"


def _ensure_instincts_dir(instincts_dir: pathlib.Path) -> None:
    """Auto-initialize ~/.claude/homunculus/instincts/ if it does not exist."""
    instincts_dir.mkdir(parents=True, exist_ok=True)


def _build_observation_template(
    session_id: str,
    captured_at: str,
    profile: str,
    tool_calls_count: int,
) -> str:
    """Build a structured instinct observation YAML template (no LLM call, ADR-016).

    Returns YAML text following the instinct schema:
    id, session_id, captured_at, observations, confidence, raw_summary.
    """
    obs_id = str(uuid.uuid4())
    return (
        f"id: {obs_id}\n"
        f"session_id: {session_id}\n"
        f"captured_at: \"{captured_at}\"\n"
        f"profile: {profile}\n"
        f"tool_calls_count: {tool_calls_count}\n"
        "observations: []\n"
        "confidence: low\n"
        "reviewed: false\n"
        "promoted: false\n"
        "raw_summary: \"\"\n"
        "notes: \"Auto-generated by Stop hook. Run /rg:learn-eval to review and promote.\"\n"
    )


def _count_pending_instincts(instincts_dir: pathlib.Path) -> int:
    """Count instinct YAML files that have not been reviewed yet."""
    count = 0
    for path in instincts_dir.glob("*.yaml"):
        try:
            content = path.read_text(encoding="utf-8")
            if "reviewed: false" in content:
                count += 1
        except Exception:
            pass
    return count


def main(
    session_data: pathlib.Path | None = None,
    instincts_dir: pathlib.Path | None = None,
) -> int:
    check_disabled()
    data_dir = session_data or SESSION_DATA
    data_dir.mkdir(parents=True, exist_ok=True)
    inst_dir = instincts_dir or HOMUNCULUS_INSTINCTS
    now = datetime.datetime.utcnow().strftime("%Y%m%dT%H%M%SZ")
    profile = get_profile()

    # Load current session if exists
    current: dict = {}
    current_path = data_dir / "current-session.json"
    if current_path.exists():
        try:
            current = json.loads(current_path.read_text(encoding="utf-8"))
        except Exception:
            current = {}

    session_id = current.get("session_id", f"sess-{now}")
    tool_calls = current.get("tool_calls", [])

    # Save summary JSON
    summary = {
        "session_id": session_id,
        "ended_at": now,
        "profile": profile,
        "tool_calls_count": len(tool_calls),
    }
    (data_dir / f"session-{now}-summary.json").write_text(
        json.dumps(summary, indent=2), encoding="utf-8"
    )

    # Save observation YAML to session-data (backward-compat) and homunculus instincts dir.
    # Errors here must NOT block session exit (ADR-016).
    try:
        obs_yaml = _build_observation_template(
            session_id=session_id,
            captured_at=now,
            profile=profile,
            tool_calls_count=len(tool_calls),
        )
        # session-data copy (existing behavior)
        (data_dir / f"session-{now}-observation.yaml").write_text(obs_yaml, encoding="utf-8")

        # homunculus instincts dir copy (SKILL-EVO-01)
        _ensure_instincts_dir(inst_dir)
        (inst_dir / f"{session_id}.yaml").write_text(obs_yaml, encoding="utf-8")

        # Notify developer of pending instincts
        pending = _count_pending_instincts(inst_dir)
        if pending > 0:
            print(
                f"[ReproGate] {pending}개의 미평가 instinct가 있습니다. "
                "/rg:learn-eval로 리뷰하세요.",
                file=sys.stderr,
            )
    except Exception as exc:
        print(f"[ReproGate] observation 저장 실패 (세션 종료는 계속됩니다): {exc}", file=sys.stderr)

    return 0


if __name__ == "__main__":
    sys.exit(main())
